### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by nulldef** [nesaulov/surrealist#53]
What's up, dude? Would you like to create alias feature for schema? Something like that
```ruby
class Person
  include Surrealist
 
  json_schema do
    {
      name: String,
      {avatar: :image}: String
    }
  end
 
  def name
    'John Doe'
  end
 
  def image
   'http://some-image.host/avatars/123.jpeg'
  end
end
```

```ruby
Person.new.surrealize 
# => { name: "John Doe", avatar: "http://some-image.host/avatars/123.jpeg" }
```

**Comment by nesaulov** [comment]
@nulldef hey, thanks for the issue. This may be a handy feature, but we should keep in mind that standard `alias_method :avatar :image` will do the job. A couple of notes on this: -
- `Surrealist::Builder` is parsing schema iteratively, so new keys can't be added to the hash on the fly, we need to perform mapping on the stage of copying of the schema (`Surrealist::SchemaDefiner`). 
- Maybe we can consider a different API for this, maybe a class method, something like:
```ruby
class Person
  include Surrealist

  json_aliases avatar: :image

  json_schema do
    { avatar: String }
  end

  def image
    'http://some-image.host/avatars/123.jpeg'
  end
end
```
- Or maybe we should leave API as you suggested, but with hash rocket instead of `:` (`{ avatar: :image } => String`)

Would you like to tackle this issue and submit a PR?

**Comment by nulldef** [comment]
I think we should use the second variant that you suggested (`json aliases`), because it seems more clear. We can use `method_missing` for catching non-existing method calling and try to lookup alias method. But it can be slowly.
Yeah, I think I can pick this issue and provide PR.

**Comment by nesaulov** [comment]
Yeah, `method_missing` is slow, I would suggest just keeping a map of aliases in some instance variable and either rescue `NoMethodError`, or tweak `Builder` (or create another class that would be responsible for this stuff).

**Comment by nulldef** [comment]
Seems to be useless
