### ISSUE TITLE
Refactor Surrealist::Builder

### ISSUE THREAD

**Issue by nesaulov** [nesaulov/surrealist#8]
`Surrealist::Builder` requires refactoring, for instance method `#take_values_from_instance` takes in 6 arguments, that seems to be too much. Specs are already present, so it should not be too hard.

**Comment by tegon** [comment]
Hi! Can I tackle this one?

**Comment by nesaulov** [comment]
@tegon sure!

**Comment by tegon** [comment]
@nesaulov Hey, so I took a look at the code and I have some ideas:

1. We  can change the class to use instance methods and make `schema` and `instance` as instance variables they're passed throughout the code;

2. Create another abstraction (maybe a `Schema` class?) and move some of the logic to it - like `assign_value` method for instance. This way we can pass an object as a parameter instead of many of them.

WDYT of these options?

**Comment by nesaulov** [comment]
@tegon hey.
The problem with instance variables is that `schema` and `instance` are different throughout the `call` method, because the method is invoked recursively, so I don't actually see a way that instance variables could help here. Though `Schema` abstraction sounds interesting to me, I reckon it will do the right thing. And passing object is also a good idea, and we need not to forget to make sure that all attributes (ex parameters) are present. Thanks!

**Comment by nesaulov** [comment]
@tegon got you, thanks for engaging anyway!

**Comment by nesaulov** [comment]
Was resolved in #34 #41 and #43
